### ISSUE TITLE
Java 9 support

### ISSUE THREAD

**Issue by cyocom** [SIMRacingApps/SIMRacingApps#131]
Currently if I open the server exe with only the Java 9 JRE, it redirects me to download Java 8.

**Comment by jfgilliam** [comment]
The launch4j tool has a fix for this. I will be including that it in the 1.6 BETA release. Since there are 2 workarounds, I'm not going to rush out a fix. Install version 8 or execute with version 9 from the command line using the following:

`java.exe -cp "%userprofile%\documents;SIMRacingAppsServer_1.5_Build_2017.12.11.exe" com.SIMRacingApps.Server`

Update the command with the version you have
