### ISSUE TITLE
"Car # Sim Not Connected"

### ISSUE THREAD

**Issue by samkatakouzinosracing** [SIMRacingApps/SIMRacingApps#218]
In a league session tonight I hear "Car # Sim Not Connected" when referring to a driver, I guess making a lap time.
I spotted exception errors in the log file. 
So I'm posting here.

[SIMRacingApps-0.log.txt.zip](https://github.com/SIMRacingApps/SIMRacingApps/files/4444486/SIMRacingApps-0.log.txt.zip)

**Comment by jfgilliam** [comment]
Thanks. The log helped a lot. Seems like the internal thread keeps restarting because of the exception. It is caused by some new code I added to track incidents by lap. This is crashing for cars that are not on the track. I added code to check the index is without the array boundaries. Will get a new release out tonight after I do some more testing.
