### ISSUE TITLE
not loading in a race

### ISSUE THREAD

**Issue by paulcorso** [SIMRacingApps/SIMRacingApps#232]
it seems to be running when i open it but does not load when i race

**Comment by jfgilliam** [comment]
It's probably because you're in full screen mode. iRacing takes over the screen in that mode. You can change to windowed mode and it will work. Here are instructions.
https://github.com/SIMRacingApps/SIMRacingApps/wiki/How-to-setup-iRacing-in-Windowed-Mode





- Jeff 

    On Friday, August 7, 2020, 07:59:31 AM EDT, paulcorso <notifications@github.com> wrote:  
 
 


it seems to be running when i open it but does not load when i race
