### ISSUE TITLE
Problems to open server on iPad

### ISSUE THREAD

**Issue by rodrigocbb** [SIMRacingApps/SIMRacingApps#250]
Hello,

Need help to open the server on my iPad. Everything worked fine for the past months but last night it simply lost connection and did not went through anymore. McAfee firewall seems to be properly set. It is set to open in all devices (doc file attached).
Please, can anyone help me with this? Thanks in advance.

[McAfee firewall.docx](https://github.com/SIMRacingApps/SIMRacingApps/files/6440646/McAffe.firewall.docx)

**Comment by jfgilliam** [comment]
I'm not that familiar with McAfee. Try disabling it temporarily. If it works, then something in McAfee is blocking it. I know with Windows Firewall, every time I update Java, I have to add a new entry for that specific version of Java.
- Jeff 

    On Friday, May 7, 2021, 05:50:40 AM EDT, rodrigocbb ***@***.***> wrote:  
 
 


Hello,

Need help to open the server on my iPad. Everything worked fine for the past months but last night it simply lost connection and did not went through anymore. McAfee firewall seems to be properly set. It is set to open in all devices (doc file attached).
Please, can anyone help me with this? Thanks in advance.

McAfee firewall.docx

**Comment by jfgilliam** [comment]
I suppose the Windows Firewall could take over if it see's that you disabled McAfee. If that happens, it will prompt you to allow it. So, do allow it. But, for the most part when devices cannot connect to the server, it's been the firewall 99% of the time.
- Jeff 

    On Friday, May 7, 2021, 08:13:43 AM EDT, rodrigocbb ***@***.***> wrote:  
 
 



I'm not that familiar with McAfee. Try disabling it temporarily. If it works, then something in McAfee is blocking it. I know with Windows Firewall, every time I update Java, I have to add a new entry for that specific version of Java. - Jeff On Friday, May 7, 2021, 05:50:40 AM EDT, rodrigocbb @.***> wrote: Hello, Need help to open the server on my iPad. Everything worked fine for the past months but last night it simply lost connection and did not went through anymore. McAfee firewall seems to be properly set. It is set to open in all devices (doc file attached). Please, can anyone help me with this? Thanks in advance. McAfee firewall.docx — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.


Thanks. If disabling McAfee doesn't work what world suggest?

**Comment by rodrigocbb** [comment]
> I suppose the Windows Firewall could take over if it see's that you disabled McAfee. If that happens, it will prompt you to allow it. So, do allow it. But, for the most part when devices cannot connect to the server, it's been the firewall 99% of the time. - Jeff On Friday, May 7, 2021, 08:13:43 AM EDT, rodrigocbb ***@***.***> wrote: I'm not that familiar with McAfee. Try disabling it temporarily. If it works, then something in McAfee is blocking it. I know with Windows Firewall, every time I update Java, I have to add a new entry for that specific version of Java. - Jeff On Friday, May 7, 2021, 05:50:40 AM EDT, rodrigocbb @.***> wrote: Hello, Need help to open the server on my iPad. Everything worked fine for the past months but last night it simply lost connection and did not went through anymore. McAfee firewall seems to be properly set. It is set to open in all devices (doc file attached). Please, can anyone help me with this? Thanks in advance. McAfee firewall.docx — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. Thanks. If disabling McAfee doesn't work what world suggest? — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

Agree,  I'm afraid not find where or which firewall though..
