### ISSUE TITLE
Pit Commands do not work in Spotter Session

### ISSUE THREAD

**Issue by CanisLupus518** [SIMRacingApps/SIMRacingApps#272]
I haven't been able to find any clear documentation on IF this should work, but I was trying to Spot for a friend (with enabling "Crew Chief" ability in the sim so that I can set their tires\fuel etc. I thought it would he helpful to use the SRA Crew Chief App to help with that, but the commands do not work in this case. 

Is this something that should work? 

Is there a way to get it to work?

Just to verify: PitCommandsSIMController=true

**Comment by jfgilliam** [comment]
The short answer is, if you can do it using iRacing's black boxes, then SRA "should" be able to do it. Sometimes the information in the black boxes is not available in the telemetry data.
Long answer, it's been years since I looked at this, so things could have changed. iRacing doesn't put much information in the telemetry about the other cars in the session. That includes the one you're spotting for. There's been numerous requests on the forums to at least provide data for the car you're spotting for, for example, they don't transmit their fuel data.
I have contemplated coding a workaround, such as peer to peer data sharing. I also contemplated using a server to act as a data forwarder. With so many firewalls and such to navigate around, these became hard to get working and would require a lot of support. It didn't seem worth it. The server would add an ongoing cost that I didn't want to have to charge for, either.
Thanks for asking.
- Jeff 

    On Saturday, October 21, 2023 at 08:27:50 PM EDT, CanisLupus518 ***@***.***> wrote:  
 
 


I haven't been able to find any clear documentation on IF this should work, but I was trying to Spot for a friend (with enabling "Crew Chief" ability in the sim so that I can set their tires\fuel etc. I thought it would he helpful to use the SRA Crew Chief App to help with that, but the commands do not work in this case.

Is this something that should work?

Is there a way to get it to work?

Just to verify: PitCommandsSIMController=true
