### ISSUE TITLE
javascript error

### ISSUE THREAD

**Issue by samster1991** [SIMRacingApps/SIMRacingApps#275]
![simracingappserror](https://github.com/SIMRacingApps/SIMRacingApps/assets/163698684/93f10275-34ed-469c-84f3-d131bf93afbc)

**Comment by jfgilliam** [comment]
I haven't quite figured out why this happens. But, it's caused by your documents folder being on OneDrive and some type of permissions error. Are you running the latest version, 1.21?. You can try the following.

1. Stop SRA if it's running.
2. Remove the folder C:\Users\samst\AppData\Local\SIMRacingApps
3. Start SRA

If that doesn't work then try this, but it will delete your configuration and you'll have to setup your widgets again.

1. Stop SRA if it's running.
2. Remove the folder C:\Users\samst\OneDrive\Documents\SIMRacingApps\storage
3. Start SRA
