### ISSUE TITLE
Pit Box: Too far forward / left / right

### ISSUE THREAD

**Issue by BadBoyClub** [SIMRacingApps/SIMRacingApps#73]
Add sound / voice announce when not in correct pit box position: too far forward / back / left / right

**Comment by jfgilliam** [comment]
I'm afraid I cannot do this because iRacing doesn't give me that level of detail in the telemetry. It tells me what percentage from the finish line is your pit stall and what percentage your car is. Even then, that has  a few meters tolerance by design. iRacing doesn't want us to know exactly were the car is for the fear of someone creating an auto drive app. I would also need to know the size of the stall.

Sorry, but good suggestion anyway. I think iRacing does use spotter packs to tell you that.
