### ISSUE TITLE
Standalone Brake Bias App

### ISSUE THREAD

**Issue by BadBoyClub** [SIMRacingApps/SIMRacingApps#77]
It would be really useful to have a brake bias only app. I have a button mapped to push BB forward or back, but have to have F8 displaying to see the adjustments. If we had a standalone app for BB I could keep my relative black boxes up all the time.

Similar to the brake pressure app in the beta, but with BB displayed only & no brake pressure as I don't need to see this

**Comment by jfgilliam** [comment]
I am going to support the capability with the yet to be created Data widget. See [Generic Data Widget](http://issues.SIMRacingApps.com/79). In 2.0, I will have the ability to create favorites, which will allow you to display any value you want using this widget. Adding this, and the many other individual values to the menu, doesn't make since for all users.

**Comment by BadBoyClub** [comment]
Even better, that's a great idea to be able to pick & mix the displays you want. Will we be able to combine them in one URL for use on tablets?

**Comment by jfgilliam** [comment]
The plan is to create a new app called AppLoader. It will read a JSON file and generate the HTML to load the Widgets specified within it. I plan to convert all the existing Apps to this format. Then, time permitting, create a visual editor to build apps with drag/drop/resize and properties. It will read/write the JSON file.

**Comment by BadBoyClub** [comment]
Sounds great, looking forward to seeing the app!

**Comment by jfgilliam** [comment]
This will be added to 1.10 as one of the Text Gauges.

**Comment by jfgilliam** [comment]
This was added to the latest beta. Download from http://downloadBETA.SIMRacingApps.com
